-- CREATE DATABASE WEBSITE;
USE WEBSITE;
-- CREATE TABLE WEBSITE(
-- 	WEBSITE_NAME VARCHAR(50) NOT NULL,
--     LINK VARCHAR(255) NOT NULL,
--     CATEGORY VARCHAR(25) NOT NULL,
--     OBJECT VARCHAR(10),
--     primary key (WEBSITE_NAME)
-- );

-- INSERT INTO WEBSITE(WEBSITE_NAME, LINK, CATEGORY, OBJECT) VALUES ('GOOGLE', 'www.google.com', 'SEARCH ENGINE', 'EVERYBODY');
-- INSERT INTO WEBSITE(WEBSITE_NAME, LINK, CATEGORY, OBJECT) VALUES ('BING', 'www.bing.com', 'SEARCH ENGINE', 'EVERYBODY');
-- INSERT INTO WEBSITE(WEBSITE_NAME, LINK, CATEGORY, OBJECT) VALUES ('BAIDU', 'www.baidu.com', 'SEARCH ENGINE', 'EVERYBODY');
-- INSERT INTO WEBSITE(WEBSITE_NAME, LINK, CATEGORY, OBJECT) VALUES ('FACEBOOK', 'www.facebook.com', 'SOCIAL', 'EVERYBODY');
-- INSERT INTO WEBSITE(WEBSITE_NAME, LINK, CATEGORY, OBJECT) VALUES ('INSTAGRAM', 'www.instagram.com', 'SOCIAL', 'EVERYBODY');
-- INSERT INTO WEBSITE(WEBSITE_NAME, LINK, CATEGORY, OBJECT) VALUES ('WECHAT', 'www.wechat.com', 'SOCIAL', 'EVERYBODY');
-- INSERT INTO WEBSITE(WEBSITE_NAME, LINK, CATEGORY, OBJECT) VALUES ('YOUTUBE', 'www.youtube.com', 'VIDEO', 'EVERYBODY');
-- INSERT INTO WEBSITE(WEBSITE_NAME, LINK, CATEGORY, OBJECT) VALUES ('BILIBILI', 'www.bilibili.com', 'VIDEO', 'EVERYBODY');
-- INSERT INTO WEBSITE(WEBSITE_NAME, LINK, CATEGORY, OBJECT) VALUES ('SPOTIFY', 'www.spotify.com', 'MUSIC', 'EVERYBODY');
-- INSERT INTO WEBSITE(WEBSITE_NAME, LINK, CATEGORY, OBJECT) VALUES ('APPLE MUSIC', 'music.apple.com', 'MUSIC', 'EVERYBODY');
-- INSERT INTO WEBSITE(WEBSITE_NAME, LINK, CATEGORY, OBJECT) VALUES ('QQ MUSIC', 'music.qq.com', 'MUSIC', 'EVERYBODY');
-- INSERT INTO WEBSITE(WEBSITE_NAME, LINK, CATEGORY, OBJECT) VALUES ('NETEASE MUSIC', 'music.163.com', 'MUSIC', 'EVERYBODY');

SELECT * FROM WEBSITE;